version: "3"

services:
  edgedb:
    image: edgedb/edgedb
    container_name: repro_edgedb
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
      EDGEDB_SERVER_PASSWORD: password
    ports:
      - "5656:5656"
